-- Default competency framework: eight sectors and five cross-sector professional competencies.
-- Idempotent: safe to run again. Edit or extend in the database; the app reads it live.

insert into public.sectors (id, name, archetype, verifier_label, evidence_types) values ('tech', 'Technology', 'project', 'Client or engineering lead', array['Shipped project', 'Client work', 'Open-source contribution', 'Internship task']) on conflict (id) do update set name = excluded.name, archetype = excluded.archetype, verifier_label = excluded.verifier_label, evidence_types = excluded.evidence_types;
insert into public.sectors (id, name, archetype, verifier_label, evidence_types) values ('marketing', 'Marketing', 'project', 'Client or agency lead', array['Campaign with results', 'Content piece', 'Client brief']) on conflict (id) do update set name = excluded.name, archetype = excluded.archetype, verifier_label = excluded.verifier_label, evidence_types = excluded.evidence_types;
insert into public.sectors (id, name, archetype, verifier_label, evidence_types) values ('economics', 'Economics', 'project', 'Supervising economist or commissioning organisation', array['Analysis or model', 'Policy brief', 'Research project']) on conflict (id) do update set name = excluded.name, archetype = excluded.archetype, verifier_label = excluded.verifier_label, evidence_types = excluded.evidence_types;
insert into public.sectors (id, name, archetype, verifier_label, evidence_types) values ('law', 'Law', 'regulated', 'Supervising lawyer', array['Clinic hours', 'Supervised drafting', 'Advocacy or moot', 'Attachment task']) on conflict (id) do update set name = excluded.name, archetype = excluded.archetype, verifier_label = excluded.verifier_label, evidence_types = excluded.evidence_types;
insert into public.sectors (id, name, archetype, verifier_label, evidence_types) values ('education', 'Education', 'regulated', 'Mentor teacher or school head', array['Practicum lesson', 'Observed lesson', 'Mentored teaching block']) on conflict (id) do update set name = excluded.name, archetype = excluded.archetype, verifier_label = excluded.verifier_label, evidence_types = excluded.evidence_types;
insert into public.sectors (id, name, archetype, verifier_label, evidence_types) values ('hospitality', 'Hospitality', 'handson', 'Duty manager', array['Assessed shift', 'Event delivered', 'Certification']) on conflict (id) do update set name = excluded.name, archetype = excluded.archetype, verifier_label = excluded.verifier_label, evidence_types = excluded.evidence_types;
insert into public.sectors (id, name, archetype, verifier_label, evidence_types) values ('fnb', 'Food and beverage', 'handson', 'Head chef or production manager', array['Assessed shift', 'Production run', 'Certification']) on conflict (id) do update set name = excluded.name, archetype = excluded.archetype, verifier_label = excluded.verifier_label, evidence_types = excluded.evidence_types;
insert into public.sectors (id, name, archetype, verifier_label, evidence_types) values ('mechanics', 'Mechanics', 'handson', 'Workshop supervisor', array['Logged repair job', 'Diagnostic case', 'Assessed workshop day']) on conflict (id) do update set name = excluded.name, archetype = excluded.archetype, verifier_label = excluded.verifier_label, evidence_types = excluded.evidence_types;

insert into public.competencies (id, sector_id, name, category) values
  ('tech-web-development', 'tech', 'Web development', 'technical'),
  ('tech-mobile-development', 'tech', 'Mobile development', 'technical'),
  ('tech-databases-and-data-modelling', 'tech', 'Databases and data modelling', 'technical'),
  ('tech-cloud-and-deployment', 'tech', 'Cloud and deployment', 'technical'),
  ('tech-version-control', 'tech', 'Version control', 'technical'),
  ('tech-testing-and-debugging', 'tech', 'Testing and debugging', 'technical'),
  ('tech-api-design', 'tech', 'API design', 'technical'),
  ('tech-cybersecurity-basics', 'tech', 'Cybersecurity basics', 'technical'),
  ('tech-ux-design', 'tech', 'UX design', 'technical'),
  ('marketing-market-research', 'marketing', 'Market research', 'technical'),
  ('marketing-brand-strategy', 'marketing', 'Brand strategy', 'technical'),
  ('marketing-content-creation', 'marketing', 'Content creation', 'technical'),
  ('marketing-social-media-management', 'marketing', 'Social media management', 'technical'),
  ('marketing-seo-and-analytics', 'marketing', 'SEO and analytics', 'technical'),
  ('marketing-paid-advertising', 'marketing', 'Paid advertising', 'technical'),
  ('marketing-campaign-planning', 'marketing', 'Campaign planning', 'technical'),
  ('marketing-copywriting', 'marketing', 'Copywriting', 'technical'),
  ('economics-data-analysis', 'economics', 'Data analysis', 'technical'),
  ('economics-econometrics', 'economics', 'Econometrics', 'technical'),
  ('economics-financial-modelling', 'economics', 'Financial modelling', 'technical'),
  ('economics-policy-analysis', 'economics', 'Policy analysis', 'technical'),
  ('economics-research-writing', 'economics', 'Research writing', 'technical'),
  ('economics-cost-benefit-analysis', 'economics', 'Cost-benefit analysis', 'technical'),
  ('economics-survey-design', 'economics', 'Survey design', 'technical'),
  ('economics-forecasting', 'economics', 'Forecasting', 'technical'),
  ('law-legal-research', 'law', 'Legal research', 'technical'),
  ('law-contract-drafting', 'law', 'Contract drafting', 'technical'),
  ('law-case-analysis', 'law', 'Case analysis', 'technical'),
  ('law-client-interviewing', 'law', 'Client interviewing', 'technical'),
  ('law-advocacy', 'law', 'Advocacy', 'technical'),
  ('law-legal-writing', 'law', 'Legal writing', 'technical'),
  ('law-regulatory-compliance', 'law', 'Regulatory compliance', 'technical'),
  ('law-professional-ethics', 'law', 'Professional ethics', 'technical'),
  ('education-lesson-planning', 'education', 'Lesson planning', 'technical'),
  ('education-classroom-management', 'education', 'Classroom management', 'technical'),
  ('education-assessment-design', 'education', 'Assessment design', 'technical'),
  ('education-inclusive-teaching', 'education', 'Inclusive teaching', 'technical'),
  ('education-subject-delivery', 'education', 'Subject delivery', 'technical'),
  ('education-learner-engagement', 'education', 'Learner engagement', 'technical'),
  ('education-educational-technology', 'education', 'Educational technology', 'technical'),
  ('education-parent-and-community-communication', 'education', 'Parent and community communication', 'technical'),
  ('hospitality-guest-service', 'hospitality', 'Guest service', 'technical'),
  ('hospitality-front-desk-operations', 'hospitality', 'Front desk operations', 'technical'),
  ('hospitality-housekeeping-standards', 'hospitality', 'Housekeeping standards', 'technical'),
  ('hospitality-food-and-beverage-service', 'hospitality', 'Food and beverage service', 'technical'),
  ('hospitality-event-coordination', 'hospitality', 'Event coordination', 'technical'),
  ('hospitality-complaint-handling', 'hospitality', 'Complaint handling', 'technical'),
  ('hospitality-food-safety-and-hygiene', 'hospitality', 'Food safety and hygiene', 'technical'),
  ('hospitality-booking-systems', 'hospitality', 'Booking systems', 'technical'),
  ('fnb-food-preparation', 'fnb', 'Food preparation', 'technical'),
  ('fnb-kitchen-station-operation', 'fnb', 'Kitchen station operation', 'technical'),
  ('fnb-food-safety-and-haccp', 'fnb', 'Food safety and HACCP', 'technical'),
  ('fnb-menu-costing', 'fnb', 'Menu costing', 'technical'),
  ('fnb-inventory-and-stock-control', 'fnb', 'Inventory and stock control', 'technical'),
  ('fnb-production-planning', 'fnb', 'Production planning', 'technical'),
  ('fnb-plating-and-presentation', 'fnb', 'Plating and presentation', 'technical'),
  ('fnb-kitchen-hygiene', 'fnb', 'Kitchen hygiene', 'technical'),
  ('mechanics-engine-diagnostics', 'mechanics', 'Engine diagnostics', 'technical'),
  ('mechanics-brakes-and-suspension', 'mechanics', 'Brakes and suspension', 'technical'),
  ('mechanics-electrical-systems', 'mechanics', 'Electrical systems', 'technical'),
  ('mechanics-servicing-and-maintenance', 'mechanics', 'Servicing and maintenance', 'technical'),
  ('mechanics-tools-and-equipment-use', 'mechanics', 'Tools and equipment use', 'technical'),
  ('mechanics-workshop-safety', 'mechanics', 'Workshop safety', 'technical'),
  ('mechanics-repair-estimation', 'mechanics', 'Repair estimation', 'technical'),
  ('mechanics-vehicle-inspection', 'mechanics', 'Vehicle inspection', 'technical'),
  ('pro-communication', null, 'Communication', 'professional'),
  ('pro-teamwork', null, 'Teamwork', 'professional'),
  ('pro-reliability', null, 'Reliability', 'professional'),
  ('pro-problem-solving', null, 'Problem-solving', 'professional'),
  ('pro-conduct', null, 'Professional conduct', 'professional')
on conflict (id) do update set name = excluded.name, sector_id = excluded.sector_id, category = excluded.category;
